name: Publish Storybook

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    # 모든 'run:' 스텝의 작업 경로를 storybook/ 로 고정
    defaults:
      run:
        working-directory: storybook

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          # 캐시 대상도 하위 폴더의 lockfile로
          cache-dependency-path: storybook/package-lock.json

      # (디버그용) 현재 폴더와 파일 확인
      - name: Show files
        run: |
          pwd
          ls -la
          cat package.json | sed -n '1,120p' || true
          echo "----- .babelrc -----"
          cat .babelrc || echo "(no .babelrc)"

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Build Storybook
        run: npm run build-storybook -- --debug-webpack

      - name: Publish to Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --storybook-build-dir=storybook-static --ci --debug
